server:
  port: 5006

telemetry:
  port: 4317
  host: localhost

kafka:
  topics:
    attachment: polyflix.attachment
    video: polyflix.video
    module: polyflix.catalog.module
    minio: polyflix.minio.attachment
  client:
    clientId: attachment-client
    brokers: localhost:29092
  consumer:
    groupId: attachment-consumer
    allowAutoTopicCreation: true

database:
  mongo:
    uri: "mongodb://root:root@localhost/attachment"

minio:
  port: 9000
  host: localhost
  ssl: false
  accessKey: minio
  secretKey: minio123
