server:
  port: 5006

telemetry:
  port: 4317
  host: localhost

kafka:
  client:
    clientId: todo-backend
    brokers: localhost:29092
  consumer:
    groupId: todo-consumer
    allowAutoTopicCreation: true

database:
  mongo:
    uri: "mongodb://root:root@localhost/attachment"
