openapi: '3.0.2'
info:
  title: Attachments OpenAPI
  version: '1.0'
components:
  schemas:
    Attachment:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          description: "The name of the attachment, should be explicit to all users"
        description:
          type: string
          description: "The description of the attachment, if it needs to be clarified."
        url:
          type: string
          description: 'The public URL of the attachment. It should be a classical URL if the attachment is a external link, or a PSU if the attachment is a file.'
      required:
        - id
        - url
  responses:
    attachmentResponse:
      description: 'An attachment'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Attachment"
    attachmentsResponse:
      description: "Returns a list of paginated attachments (for administration purposes)"
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                description: "An array of attachments"
                items:
                  $ref: "#/components/schemas/Attachment"
              limit:
                type: integer
                description: "The maximum number of attachments to return"
              offset:
                type: integer
                description: "The number of attachments to skip"    

paths:
  /:
    get:
      responses:
        '200':
          $ref: "#responses"
